; Auto-generated. Do not edit!


(cl:in-package sentry_urdf-msg)


;//! \htmlinclude pathResult.msg.html

(cl:defclass <pathResult> (roslisp-msg-protocol:ros-message)
  ((output
    :reader output
    :initarg :output
    :type cl:integer
    :initform 0)
   (final_pose
    :reader final_pose
    :initarg :final_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (goal_stamp
    :reader goal_stamp
    :initarg :goal_stamp
    :type cl:integer
    :initform 0))
)

(cl:defclass pathResult (<pathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sentry_urdf-msg:<pathResult> is deprecated: use sentry_urdf-msg:pathResult instead.")))

(cl:ensure-generic-function 'output-val :lambda-list '(m))
(cl:defmethod output-val ((m <pathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sentry_urdf-msg:output-val is deprecated.  Use sentry_urdf-msg:output instead.")
  (output m))

(cl:ensure-generic-function 'final_pose-val :lambda-list '(m))
(cl:defmethod final_pose-val ((m <pathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sentry_urdf-msg:final_pose-val is deprecated.  Use sentry_urdf-msg:final_pose instead.")
  (final_pose m))

(cl:ensure-generic-function 'goal_stamp-val :lambda-list '(m))
(cl:defmethod goal_stamp-val ((m <pathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sentry_urdf-msg:goal_stamp-val is deprecated.  Use sentry_urdf-msg:goal_stamp instead.")
  (goal_stamp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pathResult>) ostream)
  "Serializes a message object of type '<pathResult>"
  (cl:let* ((signed (cl:slot-value msg 'output)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'final_pose) ostream)
  (cl:let* ((signed (cl:slot-value msg 'goal_stamp)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pathResult>) istream)
  "Deserializes a message object of type '<pathResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'output) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'final_pose) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_stamp) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pathResult>)))
  "Returns string type for a message object of type '<pathResult>"
  "sentry_urdf/pathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pathResult)))
  "Returns string type for a message object of type 'pathResult"
  "sentry_urdf/pathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pathResult>)))
  "Returns md5sum for a message object of type '<pathResult>"
  "bd61aa226e76d94c618869ee7171e1a0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pathResult)))
  "Returns md5sum for a message object of type 'pathResult"
  "bd61aa226e76d94c618869ee7171e1a0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pathResult>)))
  "Returns full string definition for message of type '<pathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 output~%geometry_msgs/Pose final_pose~%int32 goal_stamp~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pathResult)))
  "Returns full string definition for message of type 'pathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 output~%geometry_msgs/Pose final_pose~%int32 goal_stamp~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pathResult>))
  (cl:+ 0
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'final_pose))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'pathResult
    (cl:cons ':output (output msg))
    (cl:cons ':final_pose (final_pose msg))
    (cl:cons ':goal_stamp (goal_stamp msg))
))
