; Auto-generated. Do not edit!


(cl:in-package sentry_urdf-msg)


;//! \htmlinclude pathFeedback.msg.html

(cl:defclass <pathFeedback> (roslisp-msg-protocol:ros-message)
  ((fdbk
    :reader fdbk
    :initarg :fdbk
    :type cl:integer
    :initform 0)
   (last_pose
    :reader last_pose
    :initarg :last_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass pathFeedback (<pathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sentry_urdf-msg:<pathFeedback> is deprecated: use sentry_urdf-msg:pathFeedback instead.")))

(cl:ensure-generic-function 'fdbk-val :lambda-list '(m))
(cl:defmethod fdbk-val ((m <pathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sentry_urdf-msg:fdbk-val is deprecated.  Use sentry_urdf-msg:fdbk instead.")
  (fdbk m))

(cl:ensure-generic-function 'last_pose-val :lambda-list '(m))
(cl:defmethod last_pose-val ((m <pathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sentry_urdf-msg:last_pose-val is deprecated.  Use sentry_urdf-msg:last_pose instead.")
  (last_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pathFeedback>) ostream)
  "Serializes a message object of type '<pathFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'fdbk)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'last_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pathFeedback>) istream)
  "Deserializes a message object of type '<pathFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'fdbk) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'last_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pathFeedback>)))
  "Returns string type for a message object of type '<pathFeedback>"
  "sentry_urdf/pathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pathFeedback)))
  "Returns string type for a message object of type 'pathFeedback"
  "sentry_urdf/pathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pathFeedback>)))
  "Returns md5sum for a message object of type '<pathFeedback>"
  "a0b116a1b26080da24a5e6119c80095b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pathFeedback)))
  "Returns md5sum for a message object of type 'pathFeedback"
  "a0b116a1b26080da24a5e6119c80095b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pathFeedback>)))
  "Returns full string definition for message of type '<pathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 fdbk~%geometry_msgs/Pose last_pose~%~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pathFeedback)))
  "Returns full string definition for message of type 'pathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 fdbk~%geometry_msgs/Pose last_pose~%~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pathFeedback>))
  (cl:+ 0
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'last_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'pathFeedback
    (cl:cons ':fdbk (fdbk msg))
    (cl:cons ':last_pose (last_pose msg))
))
