// Generated by gencpp from file mapping_and_control/path.msg
// DO NOT EDIT!


#ifndef MAPPING_AND_CONTROL_MESSAGE_PATH_H
#define MAPPING_AND_CONTROL_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <mapping_and_control/pathRequest.h>
#include <mapping_and_control/pathResponse.h>


namespace mapping_and_control
{

struct path
{

typedef pathRequest Request;
typedef pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path
} // namespace mapping_and_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mapping_and_control::path > {
  static const char* value()
  {
    return "87fbad184f990f6671a31d6fd2678f60";
  }

  static const char* value(const ::mapping_and_control::path&) { return value(); }
};

template<>
struct DataType< ::mapping_and_control::path > {
  static const char* value()
  {
    return "mapping_and_control/path";
  }

  static const char* value(const ::mapping_and_control::path&) { return value(); }
};


// service_traits::MD5Sum< ::mapping_and_control::pathRequest> should match 
// service_traits::MD5Sum< ::mapping_and_control::path > 
template<>
struct MD5Sum< ::mapping_and_control::pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mapping_and_control::path >::value();
  }
  static const char* value(const ::mapping_and_control::pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping_and_control::pathRequest> should match 
// service_traits::DataType< ::mapping_and_control::path > 
template<>
struct DataType< ::mapping_and_control::pathRequest>
{
  static const char* value()
  {
    return DataType< ::mapping_and_control::path >::value();
  }
  static const char* value(const ::mapping_and_control::pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mapping_and_control::pathResponse> should match 
// service_traits::MD5Sum< ::mapping_and_control::path > 
template<>
struct MD5Sum< ::mapping_and_control::pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mapping_and_control::path >::value();
  }
  static const char* value(const ::mapping_and_control::pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapping_and_control::pathResponse> should match 
// service_traits::DataType< ::mapping_and_control::path > 
template<>
struct DataType< ::mapping_and_control::pathResponse>
{
  static const char* value()
  {
    return DataType< ::mapping_and_control::path >::value();
  }
  static const char* value(const ::mapping_and_control::pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAPPING_AND_CONTROL_MESSAGE_PATH_H
