// Generated by gencpp from file example_gazebo_set_state/SrvIntRequest.msg
// DO NOT EDIT!


#ifndef EXAMPLE_GAZEBO_SET_STATE_MESSAGE_SRVINTREQUEST_H
#define EXAMPLE_GAZEBO_SET_STATE_MESSAGE_SRVINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example_gazebo_set_state
{
template <class ContainerAllocator>
struct SrvIntRequest_
{
  typedef SrvIntRequest_<ContainerAllocator> Type;

  SrvIntRequest_()
    : request_int(0)  {
    }
  SrvIntRequest_(const ContainerAllocator& _alloc)
    : request_int(0)  {
  (void)_alloc;
    }



   typedef int32_t _request_int_type;
  _request_int_type request_int;




  typedef boost::shared_ptr< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvIntRequest_

typedef ::example_gazebo_set_state::SrvIntRequest_<std::allocator<void> > SrvIntRequest;

typedef boost::shared_ptr< ::example_gazebo_set_state::SrvIntRequest > SrvIntRequestPtr;
typedef boost::shared_ptr< ::example_gazebo_set_state::SrvIntRequest const> SrvIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace example_gazebo_set_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'gazebo_msgs': ['/opt/ros/indigo/share/gazebo_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3178d1d7ec6cecacf3be2661f2752839";
  }

  static const char* value(const ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3178d1d7ec6cecacULL;
  static const uint64_t static_value2 = 0xf3be2661f2752839ULL;
};

template<class ContainerAllocator>
struct DataType< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_gazebo_set_state/SrvIntRequest";
  }

  static const char* value(const ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 request_int\n\
";
  }

  static const char* value(const ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_gazebo_set_state::SrvIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_int: ";
    Printer<int32_t>::stream(s, indent + "  ", v.request_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_GAZEBO_SET_STATE_MESSAGE_SRVINTREQUEST_H
