// Generated by gencpp from file sentry_urdf/pathResult.msg
// DO NOT EDIT!


#ifndef SENTRY_URDF_MESSAGE_PATHRESULT_H
#define SENTRY_URDF_MESSAGE_PATHRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace sentry_urdf
{
template <class ContainerAllocator>
struct pathResult_
{
  typedef pathResult_<ContainerAllocator> Type;

  pathResult_()
    : output(0)
    , final_pose()
    , goal_stamp(0)  {
    }
  pathResult_(const ContainerAllocator& _alloc)
    : output(0)
    , final_pose(_alloc)
    , goal_stamp(0)  {
  (void)_alloc;
    }



   typedef int32_t _output_type;
  _output_type output;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _final_pose_type;
  _final_pose_type final_pose;

   typedef int32_t _goal_stamp_type;
  _goal_stamp_type goal_stamp;




  typedef boost::shared_ptr< ::sentry_urdf::pathResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentry_urdf::pathResult_<ContainerAllocator> const> ConstPtr;

}; // struct pathResult_

typedef ::sentry_urdf::pathResult_<std::allocator<void> > pathResult;

typedef boost::shared_ptr< ::sentry_urdf::pathResult > pathResultPtr;
typedef boost::shared_ptr< ::sentry_urdf::pathResult const> pathResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentry_urdf::pathResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentry_urdf::pathResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sentry_urdf

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/indigo/share/roscpp/cmake/../msg'], 'sentry_urdf': ['/home/mdas/ros_ws/devel/share/sentry_urdf/msg'], 'actionlib': ['/opt/ros/indigo/share/actionlib/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sentry_urdf::pathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_urdf::pathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentry_urdf::pathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentry_urdf::pathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_urdf::pathResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_urdf::pathResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentry_urdf::pathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd61aa226e76d94c618869ee7171e1a0";
  }

  static const char* value(const ::sentry_urdf::pathResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd61aa226e76d94cULL;
  static const uint64_t static_value2 = 0x618869ee7171e1a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentry_urdf::pathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentry_urdf/pathResult";
  }

  static const char* value(const ::sentry_urdf::pathResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentry_urdf::pathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 output\n\
geometry_msgs/Pose final_pose\n\
int32 goal_stamp\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::sentry_urdf::pathResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentry_urdf::pathResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.final_pose);
      stream.next(m.goal_stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentry_urdf::pathResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentry_urdf::pathResult_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output);
    s << indent << "final_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_pose);
    s << indent << "goal_stamp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTRY_URDF_MESSAGE_PATHRESULT_H
