# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stdr_msgs/RegisterRobotActionResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import stdr_msgs.msg
import geometry_msgs.msg
import genpy
import actionlib_msgs.msg
import std_msgs.msg

class RegisterRobotActionResult(genpy.Message):
  _md5sum = "ce3f59972017deeb55ae45b800a1a53d"
  _type = "stdr_msgs/RegisterRobotActionResult"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
RegisterRobotResult result

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: stdr_msgs/RegisterRobotResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#result definition
stdr_msgs/RobotMsg description

================================================================================
MSG: stdr_msgs/RobotMsg
geometry_msgs/Pose2D initialPose

stdr_msgs/FootprintMsg footprint

stdr_msgs/LaserSensorMsg[] laserSensors
stdr_msgs/SonarSensorMsg[] sonarSensors
stdr_msgs/RfidSensorMsg[] rfidSensors
stdr_msgs/CO2SensorMsg[] co2Sensors
stdr_msgs/SoundSensorMsg[] soundSensors
stdr_msgs/ThermalSensorMsg[] thermalSensors

stdr_msgs/KinematicMsg kinematicModel

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
================================================================================
MSG: stdr_msgs/FootprintMsg
geometry_msgs/Point[] points
float32 radius # for circular footprints

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: stdr_msgs/LaserSensorMsg
# Laser Sensor description
float32 maxAngle
float32 minAngle
float32 maxRange
float32 minRange
int32 numRays

stdr_msgs/Noise noise

float32 frequency

string frame_id
geometry_msgs/Pose2D pose # sensor pose, relative to robot center

================================================================================
MSG: stdr_msgs/Noise
bool noise
float32 noiseMean
float32 noiseStd

================================================================================
MSG: stdr_msgs/SonarSensorMsg
# Rfid sensor description
float32 maxRange
float32 minRange
float32 coneAngle

float32 frequency
stdr_msgs/Noise noise

string frame_id
geometry_msgs/Pose2D pose # sensor pose, relative to robot center

================================================================================
MSG: stdr_msgs/RfidSensorMsg
# Rfid sensor description
float32 maxRange
float32 angleSpan
float32 signalCutoff

float32 frequency

string frame_id
geometry_msgs/Pose2D pose # sensor pose, relative to robot center

================================================================================
MSG: stdr_msgs/CO2SensorMsg
# Sensor description

float32 maxRange
float32 frequency
string frame_id

# sensor pose, relative to robot center
geometry_msgs/Pose2D pose 

================================================================================
MSG: stdr_msgs/SoundSensorMsg
# Sensor description

float32 maxRange
float32 frequency
float32 angleSpan
string frame_id

# sensor pose, relative to robot center
geometry_msgs/Pose2D pose 

================================================================================
MSG: stdr_msgs/ThermalSensorMsg
# Sensor description

float32 maxRange
float32 frequency
float32 angleSpan
string frame_id

# sensor pose, relative to robot center
geometry_msgs/Pose2D pose 

================================================================================
MSG: stdr_msgs/KinematicMsg
# Container for the kinematic model parameters. The parameters selected/
# are quite general. For a more accurate motion model a per-kinematic model
# approach should be followed.
# Parameters are in the form a_C_D, where C is affected by D.
# ux is the linear speed
# uy is the lateral speed (for omni vehicles)
# w is the angular speed
# g is a cofficient that directly affects the angular speed
# For more information check the MotionController::sampleVelocities function.

string type
float32 a_ux_ux
float32 a_ux_uy
float32 a_ux_w
float32 a_uy_ux
float32 a_uy_uy
float32 a_uy_w
float32 a_w_ux
float32 a_w_uy
float32 a_w_w
float32 a_g_ux
float32 a_g_uy
float32 a_g_w
"""
  __slots__ = ['header','status','result']
  _slot_types = ['std_msgs/Header','actionlib_msgs/GoalStatus','stdr_msgs/RegisterRobotResult']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,status,result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RegisterRobotActionResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.result is None:
        self.result = stdr_msgs.msg.RegisterRobotResult()
    else:
      self.header = std_msgs.msg.Header()
      self.status = actionlib_msgs.msg.GoalStatus()
      self.result = stdr_msgs.msg.RegisterRobotResult()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs))
      _x = self.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.status.status))
      _x = self.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.result.description.initialPose.x, _x.result.description.initialPose.y, _x.result.description.initialPose.theta))
      length = len(self.result.description.footprint.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.footprint.points:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      buff.write(_struct_f.pack(self.result.description.footprint.radius))
      length = len(self.result.description.laserSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.laserSensors:
        _x = val1
        buff.write(_struct_4fi.pack(_x.maxAngle, _x.minAngle, _x.maxRange, _x.minRange, _x.numRays))
        _v1 = val1.noise
        _x = _v1
        buff.write(_struct_B2f.pack(_x.noise, _x.noiseMean, _x.noiseStd))
        buff.write(_struct_f.pack(val1.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v2 = val1.pose
        _x = _v2
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.sonarSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.sonarSensors:
        _x = val1
        buff.write(_struct_4f.pack(_x.maxRange, _x.minRange, _x.coneAngle, _x.frequency))
        _v3 = val1.noise
        _x = _v3
        buff.write(_struct_B2f.pack(_x.noise, _x.noiseMean, _x.noiseStd))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v4 = val1.pose
        _x = _v4
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.rfidSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.rfidSensors:
        _x = val1
        buff.write(_struct_4f.pack(_x.maxRange, _x.angleSpan, _x.signalCutoff, _x.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v5 = val1.pose
        _x = _v5
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.co2Sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.co2Sensors:
        _x = val1
        buff.write(_struct_2f.pack(_x.maxRange, _x.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v6 = val1.pose
        _x = _v6
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.soundSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.soundSensors:
        _x = val1
        buff.write(_struct_3f.pack(_x.maxRange, _x.frequency, _x.angleSpan))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v7 = val1.pose
        _x = _v7
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.thermalSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.thermalSensors:
        _x = val1
        buff.write(_struct_3f.pack(_x.maxRange, _x.frequency, _x.angleSpan))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v8 = val1.pose
        _x = _v8
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      _x = self.result.description.kinematicModel.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12f.pack(_x.result.description.kinematicModel.a_ux_ux, _x.result.description.kinematicModel.a_ux_uy, _x.result.description.kinematicModel.a_ux_w, _x.result.description.kinematicModel.a_uy_ux, _x.result.description.kinematicModel.a_uy_uy, _x.result.description.kinematicModel.a_uy_w, _x.result.description.kinematicModel.a_w_ux, _x.result.description.kinematicModel.a_w_uy, _x.result.description.kinematicModel.a_w_w, _x.result.description.kinematicModel.a_g_ux, _x.result.description.kinematicModel.a_g_uy, _x.result.description.kinematicModel.a_g_w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.result is None:
        self.result = stdr_msgs.msg.RegisterRobotResult()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.goal_id.id = str[start:end].decode('utf-8')
      else:
        self.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.text = str[start:end].decode('utf-8')
      else:
        self.status.text = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.result.description.initialPose.x, _x.result.description.initialPose.y, _x.result.description.initialPose.theta,) = _struct_3d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.footprint.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.result.description.footprint.points.append(val1)
      start = end
      end += 4
      (self.result.description.footprint.radius,) = _struct_f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.laserSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.LaserSensorMsg()
        _x = val1
        start = end
        end += 20
        (_x.maxAngle, _x.minAngle, _x.maxRange, _x.minRange, _x.numRays,) = _struct_4fi.unpack(str[start:end])
        _v9 = val1.noise
        _x = _v9
        start = end
        end += 9
        (_x.noise, _x.noiseMean, _x.noiseStd,) = _struct_B2f.unpack(str[start:end])
        _v9.noise = bool(_v9.noise)
        start = end
        end += 4
        (val1.frequency,) = _struct_f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v10 = val1.pose
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.laserSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.sonarSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.SonarSensorMsg()
        _x = val1
        start = end
        end += 16
        (_x.maxRange, _x.minRange, _x.coneAngle, _x.frequency,) = _struct_4f.unpack(str[start:end])
        _v11 = val1.noise
        _x = _v11
        start = end
        end += 9
        (_x.noise, _x.noiseMean, _x.noiseStd,) = _struct_B2f.unpack(str[start:end])
        _v11.noise = bool(_v11.noise)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v12 = val1.pose
        _x = _v12
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.sonarSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.rfidSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.RfidSensorMsg()
        _x = val1
        start = end
        end += 16
        (_x.maxRange, _x.angleSpan, _x.signalCutoff, _x.frequency,) = _struct_4f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v13 = val1.pose
        _x = _v13
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.rfidSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.co2Sensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.CO2SensorMsg()
        _x = val1
        start = end
        end += 8
        (_x.maxRange, _x.frequency,) = _struct_2f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v14 = val1.pose
        _x = _v14
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.co2Sensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.soundSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.SoundSensorMsg()
        _x = val1
        start = end
        end += 12
        (_x.maxRange, _x.frequency, _x.angleSpan,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v15 = val1.pose
        _x = _v15
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.soundSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.thermalSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.ThermalSensorMsg()
        _x = val1
        start = end
        end += 12
        (_x.maxRange, _x.frequency, _x.angleSpan,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v16 = val1.pose
        _x = _v16
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.thermalSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.description.kinematicModel.type = str[start:end].decode('utf-8')
      else:
        self.result.description.kinematicModel.type = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.result.description.kinematicModel.a_ux_ux, _x.result.description.kinematicModel.a_ux_uy, _x.result.description.kinematicModel.a_ux_w, _x.result.description.kinematicModel.a_uy_ux, _x.result.description.kinematicModel.a_uy_uy, _x.result.description.kinematicModel.a_uy_w, _x.result.description.kinematicModel.a_w_ux, _x.result.description.kinematicModel.a_w_uy, _x.result.description.kinematicModel.a_w_w, _x.result.description.kinematicModel.a_g_ux, _x.result.description.kinematicModel.a_g_uy, _x.result.description.kinematicModel.a_g_w,) = _struct_12f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs))
      _x = self.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.status.status))
      _x = self.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.result.description.initialPose.x, _x.result.description.initialPose.y, _x.result.description.initialPose.theta))
      length = len(self.result.description.footprint.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.footprint.points:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      buff.write(_struct_f.pack(self.result.description.footprint.radius))
      length = len(self.result.description.laserSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.laserSensors:
        _x = val1
        buff.write(_struct_4fi.pack(_x.maxAngle, _x.minAngle, _x.maxRange, _x.minRange, _x.numRays))
        _v17 = val1.noise
        _x = _v17
        buff.write(_struct_B2f.pack(_x.noise, _x.noiseMean, _x.noiseStd))
        buff.write(_struct_f.pack(val1.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v18 = val1.pose
        _x = _v18
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.sonarSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.sonarSensors:
        _x = val1
        buff.write(_struct_4f.pack(_x.maxRange, _x.minRange, _x.coneAngle, _x.frequency))
        _v19 = val1.noise
        _x = _v19
        buff.write(_struct_B2f.pack(_x.noise, _x.noiseMean, _x.noiseStd))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v20 = val1.pose
        _x = _v20
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.rfidSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.rfidSensors:
        _x = val1
        buff.write(_struct_4f.pack(_x.maxRange, _x.angleSpan, _x.signalCutoff, _x.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v21 = val1.pose
        _x = _v21
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.co2Sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.co2Sensors:
        _x = val1
        buff.write(_struct_2f.pack(_x.maxRange, _x.frequency))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v22 = val1.pose
        _x = _v22
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.soundSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.soundSensors:
        _x = val1
        buff.write(_struct_3f.pack(_x.maxRange, _x.frequency, _x.angleSpan))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v23 = val1.pose
        _x = _v23
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      length = len(self.result.description.thermalSensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.result.description.thermalSensors:
        _x = val1
        buff.write(_struct_3f.pack(_x.maxRange, _x.frequency, _x.angleSpan))
        _x = val1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _v24 = val1.pose
        _x = _v24
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
      _x = self.result.description.kinematicModel.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12f.pack(_x.result.description.kinematicModel.a_ux_ux, _x.result.description.kinematicModel.a_ux_uy, _x.result.description.kinematicModel.a_ux_w, _x.result.description.kinematicModel.a_uy_ux, _x.result.description.kinematicModel.a_uy_uy, _x.result.description.kinematicModel.a_uy_w, _x.result.description.kinematicModel.a_w_ux, _x.result.description.kinematicModel.a_w_uy, _x.result.description.kinematicModel.a_w_w, _x.result.description.kinematicModel.a_g_ux, _x.result.description.kinematicModel.a_g_uy, _x.result.description.kinematicModel.a_g_w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = actionlib_msgs.msg.GoalStatus()
      if self.result is None:
        self.result = stdr_msgs.msg.RegisterRobotResult()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.status.goal_id.stamp.secs, _x.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.goal_id.id = str[start:end].decode('utf-8')
      else:
        self.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.text = str[start:end].decode('utf-8')
      else:
        self.status.text = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.result.description.initialPose.x, _x.result.description.initialPose.y, _x.result.description.initialPose.theta,) = _struct_3d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.footprint.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.result.description.footprint.points.append(val1)
      start = end
      end += 4
      (self.result.description.footprint.radius,) = _struct_f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.laserSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.LaserSensorMsg()
        _x = val1
        start = end
        end += 20
        (_x.maxAngle, _x.minAngle, _x.maxRange, _x.minRange, _x.numRays,) = _struct_4fi.unpack(str[start:end])
        _v25 = val1.noise
        _x = _v25
        start = end
        end += 9
        (_x.noise, _x.noiseMean, _x.noiseStd,) = _struct_B2f.unpack(str[start:end])
        _v25.noise = bool(_v25.noise)
        start = end
        end += 4
        (val1.frequency,) = _struct_f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v26 = val1.pose
        _x = _v26
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.laserSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.sonarSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.SonarSensorMsg()
        _x = val1
        start = end
        end += 16
        (_x.maxRange, _x.minRange, _x.coneAngle, _x.frequency,) = _struct_4f.unpack(str[start:end])
        _v27 = val1.noise
        _x = _v27
        start = end
        end += 9
        (_x.noise, _x.noiseMean, _x.noiseStd,) = _struct_B2f.unpack(str[start:end])
        _v27.noise = bool(_v27.noise)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v28 = val1.pose
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.sonarSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.rfidSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.RfidSensorMsg()
        _x = val1
        start = end
        end += 16
        (_x.maxRange, _x.angleSpan, _x.signalCutoff, _x.frequency,) = _struct_4f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v29 = val1.pose
        _x = _v29
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.rfidSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.co2Sensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.CO2SensorMsg()
        _x = val1
        start = end
        end += 8
        (_x.maxRange, _x.frequency,) = _struct_2f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v30 = val1.pose
        _x = _v30
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.co2Sensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.soundSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.SoundSensorMsg()
        _x = val1
        start = end
        end += 12
        (_x.maxRange, _x.frequency, _x.angleSpan,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v31 = val1.pose
        _x = _v31
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.soundSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.result.description.thermalSensors = []
      for i in range(0, length):
        val1 = stdr_msgs.msg.ThermalSensorMsg()
        _x = val1
        start = end
        end += 12
        (_x.maxRange, _x.frequency, _x.angleSpan,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame_id = str[start:end].decode('utf-8')
        else:
          val1.frame_id = str[start:end]
        _v32 = val1.pose
        _x = _v32
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.result.description.thermalSensors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.description.kinematicModel.type = str[start:end].decode('utf-8')
      else:
        self.result.description.kinematicModel.type = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.result.description.kinematicModel.a_ux_ux, _x.result.description.kinematicModel.a_ux_uy, _x.result.description.kinematicModel.a_ux_w, _x.result.description.kinematicModel.a_uy_ux, _x.result.description.kinematicModel.a_uy_uy, _x.result.description.kinematicModel.a_uy_w, _x.result.description.kinematicModel.a_w_ux, _x.result.description.kinematicModel.a_w_uy, _x.result.description.kinematicModel.a_w_w, _x.result.description.kinematicModel.a_g_ux, _x.result.description.kinematicModel.a_g_uy, _x.result.description.kinematicModel.a_g_w,) = _struct_12f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_4fi = struct.Struct("<4fi")
_struct_12f = struct.Struct("<12f")
_struct_f = struct.Struct("<f")
_struct_2f = struct.Struct("<2f")
_struct_3f = struct.Struct("<3f")
_struct_3I = struct.Struct("<3I")
_struct_4f = struct.Struct("<4f")
_struct_B2f = struct.Struct("<B2f")
_struct_2I = struct.Struct("<2I")
_struct_3d = struct.Struct("<3d")
