# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sentry_urdf/pathFeedback.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class pathFeedback(genpy.Message):
  _md5sum = "a0b116a1b26080da24a5e6119c80095b"
  _type = "sentry_urdf/pathFeedback"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback
int32 fdbk
geometry_msgs/Pose last_pose



================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['fdbk','last_pose']
  _slot_types = ['int32','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fdbk,last_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pathFeedback, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fdbk is None:
        self.fdbk = 0
      if self.last_pose is None:
        self.last_pose = geometry_msgs.msg.Pose()
    else:
      self.fdbk = 0
      self.last_pose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i7d.pack(_x.fdbk, _x.last_pose.position.x, _x.last_pose.position.y, _x.last_pose.position.z, _x.last_pose.orientation.x, _x.last_pose.orientation.y, _x.last_pose.orientation.z, _x.last_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.last_pose is None:
        self.last_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.fdbk, _x.last_pose.position.x, _x.last_pose.position.y, _x.last_pose.position.z, _x.last_pose.orientation.x, _x.last_pose.orientation.y, _x.last_pose.orientation.z, _x.last_pose.orientation.w,) = _struct_i7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i7d.pack(_x.fdbk, _x.last_pose.position.x, _x.last_pose.position.y, _x.last_pose.position.z, _x.last_pose.orientation.x, _x.last_pose.orientation.y, _x.last_pose.orientation.z, _x.last_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.last_pose is None:
        self.last_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.fdbk, _x.last_pose.position.x, _x.last_pose.position.y, _x.last_pose.position.z, _x.last_pose.orientation.x, _x.last_pose.orientation.y, _x.last_pose.orientation.z, _x.last_pose.orientation.w,) = _struct_i7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i7d = struct.Struct("<i7d")
